//! Thread-confined native state; lifecycle teardown belongs to construction.rs.
use super::*;

pub(super) struct WebGl {
    // Delete resources while their owning context is current, before EGL teardown.
    pub(super) native: NativeContext,
    pub(super) core: Option<core_entries::CoreEntries>,
    pub(super) core_buffer_bindings: HashMap<u32, u32>,
    pub(super) surface: Surface,
    pub(super) readback_cache: readback_cache::Cache,
    pub(super) shader_validation_cache: shader_validation_cache::Cache,
    pub(super) shader_validators: shader_validators::Validators,
    pub(super) pending_links: pending_links::PendingLinks,
    pub(super) compiler_events: compiler_events::Events,
    pub(super) uniform_reflection: uniform_reflection::Cache,
    pub(super) attribute_reflection: attribute_reflection::Cache,
    pub(super) index_cache: index_cache::Cache,
    pub(super) objects: Objects,
    pub(super) errors: VecDeque<u32>,
    pub(super) options: Options,
    pub(super) stencil_masks: stencil_masks::StencilMasks,
    pub(super) resource_bytes: usize,
    pub(super) resource_limit: usize,
    pub(super) resource_diagnostics: resource_diagnostics::Ledger,
    pub(super) execution_profile: execution_profile::Profile,
    pub(super) array_buffer: u32,
    pub(super) element_buffer: u32,
    pub(super) program: u32,
    pub(super) attributes: Vec<buffers::Attribute>,
    pub(super) attribute_values: Vec<vertex_attributes::ValueKind>,
    pub(super) extensions: extensions::Extensions,
    pub(super) vertex_arrays: vertex_arrays::VertexArrays,
    pub(super) framebuffer: u32,
    pub(super) read_framebuffer: u32,
    pub(super) default_read_buffer: u32,
    pub(super) renderbuffer: u32,
    pub(super) texture_unit: usize,
    pub(super) textures: Vec<[u32; 4]>,
    pub(super) samplers: Vec<u32>,
    pub(super) indexed_uniforms: indexed_uniform_buffers::Bindings,
    pub(super) query_objects: query_objects::State,
    pub(super) sync_objects: sync_objects::State,
    pub(super) transform_feedback: transform_feedback::State,
    pub(super) default_draw_buffer: u32,
}
