// Shared WebGL bootstrap: Window and Worker must register the same APIs.
macro_rules! webgl_bootstrap {
    () => {
        concat!(
    include_str!("bootstrap/webgl_private_wire.js"),
    include_str!("bootstrap/webgl_attributes.js"),
    include_str!("bootstrap/webgl_private_brands.js"),
    include_str!("bootstrap/webgl_context.js"),
    include_str!("bootstrap/webgl_reflection_records.js"),
    include_str!("bootstrap/webgl_argument_brands.js"),
    include_str!("bootstrap/webgl_numeric_arguments.js"),
    include_str!("bootstrap/webgl_lifecycle.js"),
    include_str!("bootstrap/webgl_extensions.js"),
    include_str!("bootstrap/webgl_texture_extensions.js"),
    include_str!("bootstrap/webgl_compressed_extensions.js"),
    include_str!("bootstrap/webgl_draw_buffers.js"),
    include_str!("bootstrap/webgl_vertex_arrays.js"),
    include_str!("bootstrap/webgl_methods.js"),
    include_str!("bootstrap/webgl_queries.js"),
    include_str!("bootstrap/webgl_video_sources.js"),
    include_str!("bootstrap/webgl_textures.js"),
    include_str!("bootstrap/webgl_constants.js"),
    include_str!("bootstrap/webgl2_context.js"),
    include_str!("bootstrap/webgl2_constants.js"),
    include_str!("bootstrap/webgl2_data.js"),
    include_str!("bootstrap/webgl_multi_draw.js"),
    include_str!("bootstrap/webgl_indexed_blend.js"),
    include_str!("bootstrap/webgl2_image_packing.js"),
    include_str!("bootstrap/webgl2_view_pixels.js"),
    include_str!("bootstrap/webgl2_image_sources.js"),
    include_str!("bootstrap/webgl2_pixels.js"),
    include_str!("bootstrap/webgl2_texture2d.js"),
    include_str!("bootstrap/webgl2_compressed_textures.js"),
    include_str!("bootstrap/webgl2_objects.js"),
    include_str!("bootstrap/webgl2_sync.js"),
    include_str!("bootstrap/webgl2_framebuffers.js"),
    include_str!("bootstrap/webgl2_buffers.js"),
    include_str!("bootstrap/webgl2_queries.js"),
    include_str!("bootstrap/webgl2_uniform_blocks.js"),
    include_str!("bootstrap/webgl2_uniforms.js"),
    include_str!("bootstrap/webgl2_vertex_attributes.js"),
        )
    };
}
pub(super) use webgl_bootstrap;
